name: age_counter_app
description: A simple Flutter Age Counter app using Provider for state management.

# Specifies the environment in which this project runs
environment:
  sdk: ">=2.17.0 <3.0.0" # The Flutter SDK version range required for this project

# Dependencies for the project
dependencies:
  flutter:
    sdk: flutter # The Flutter SDK dependency
  provider: ^6.1.2 # The Provider package used for state management
  desktop_window: 0.4.0  # This package can be used for window sizing on desktop platforms, though it's optional if desktop-specific functionality is not needed

# Development dependencies used for testing the app
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true # Enables Material Design icons and components
